const std = @import("std");

pub const OpCode = enum(u8) {
    constant,
    pop,
    add,
    subtract,
    multiply,
    divide,
    modulus,
    negate,
    not,
    @"or",
    @"and",
    true,
    false,
    nil,
    equal,
    not_equal,
    greater_than,
    greater_than_equal,
    jump,
    jump_if_false,
    prong,
    decl_global,
    get_global,
    set_global,
    get_local,
    set_local,
    set_property,
    get_upvalue,
    set_upvalue,
    string,
    loc,
    list,
    map,
    set,
    instance,
    range,
    iter_start,
    iter_next,
    iter_end,
    index,
    call,
    dialogue,
    fork,
    choice,
    divert,
    backup,
    return_void,
    return_value,
    visit,
    fin,

    pub fn toString(self: OpCode) []const u8 {
        return switch (self) {
            .constant => "OP_CONSTANT",
            .pop => "OP_POP",
            .add => "OP_ADD",
            .subtract => "OP_SUBTRACT",
            .multiply => "OP_MULTIPLY",
            .divide => "OP_DIVIDE",
            .modulus => "OP_MODULUS",
            .negate => "OP_NEGATE",
            .not => "OP_NOT",
            .@"or" => "OP_OR",
            .@"and" => "OP_AND",
            .true => "OP_TRUE",
            .false => "OP_FALSE",
            .nil => "OP_NIL",
            .equal => "OP_EQUAL",
            .not_equal => "OP_NOT_EQUAL",
            .greater_than => "OP_GREATER_THAN",
            .greater_than_equal => "OP_GREATER_THAN_EQUAL",
            .jump => "OP_JUMP",
            .jump_if_false => "OP_JUMP_IF_FALSE",
            .prong => "OP_PRONG",
            .decl_global => "OP_DECL_GLOBAL",
            .get_global => "OP_GET_GLOBAL",
            .set_global => "OP_SET_GLOBAL",
            .get_local => "OP_GET_LOCAL",
            .set_local => "OP_SET_LOCAL",
            .set_property => "OP_SET_PROPERTY",
            .get_upvalue => "OP_GET_UPVALUE",
            .set_upvalue => "OP_SET_UPVALUE",
            .list => "OP_LIST",
            .string => "OP_STRING",
            .loc => "OP_LOC",
            .map => "OP_MAP",
            .set => "OP_SET",
            .instance => "OP_INSTANCE",
            .range => "OP_RANGE",
            .iter_start => "OP_ITER_START",
            .iter_next => "OP_ITER_NEXT",
            .iter_end => "OP_ITER_END",
            .index => "OP_INDEX",
            .call => "OP_CALL",
            .dialogue => "OP_DIALOGUE",
            .fork => "OP_FORK",
            .choice => "OP_CHOICE",
            .backup => "OP_BACKUP",
            .return_void => "OP_RETURN_VOID",
            .return_value => "OP_RETURN_VALUE",
            .visit => "OP_VISIT",
            .divert => "OP_DIVERT",
            .fin => "OP_FIN",
        };
    }
};
