const std = @import("std");

pub const Token = struct {
    token_type: TokenType,
    start: usize,
    end: usize,
    line: usize,
    column: usize,
    file_index: usize,

    pub fn eql(self: Token, other: Token) bool {
        return self.token_type == other.token_type and
            self.start == other.start and
            self.end == other.end and
            self.file_index == other.file_index;
    }

    pub fn toString(token_type: TokenType) []const u8 {
        return switch (token_type) {
            .left_paren => "(",
            .right_paren => ")",
            .left_brace => "{{",
            .right_brace => "}}",
            .left_bracket => "[",
            .right_bracket => "]",

            .at => "@",
            .caret => "^",
            .colon => ":",
            .comma => ",",
            .dot => ".",
            .dot_dot => "..",
            .hash => "#",
            .minus => "-",
            .percent => "%",
            .plus => "+",
            .pipe => "|",
            .semi_colon => ":",
            .slash => "/",
            .star => "*",
            .tilde => "~",
            .minus_equal => "-=",
            .percent_equal => "%=",
            .plus_equal => "+=",
            .slash_equal => "/=",
            .star_equal => "*=",

            .bang => "!",
            .bang_equal => "!=",
            .equal => "=",
            .equal_equal => "==",
            .greater => ">",
            .greater_equal => ">=",
            .less => "<",
            .less_equal => "<=",

            .identifier => "[identifier]",
            .number => "[number]",
            .string => "[string]",

            .as => "as",
            .@"and" => "and",
            .@"break" => "break",
            .@"const" => "const",
            .@"continue" => "continue",
            .@"else" => "else",
            .@"enum" => "enum",
            .enumseq => "enumseq",
            .@"extern" => "extern",
            .false => "false",
            .@"fn" => "fn",
            .@"for" => "for",
            .@"if" => "if",
            .include => "include",
            .list => "List",
            .map => "Map",
            .new => "new",
            .nil => "nil",
            .@"or" => "or",
            .@"return" => "return",
            .self => "self",
            .seq => "seq",
            .set => "Set",
            .class => "class",
            .@"switch" => "switch",
            .true => "true",
            .@"var" => "var",
            .void => "void",
            .@"while" => "while",

            .bough => "bough",
            .divert => "=>",
            .fork => "fork",
            .fin => "fin",

            .comment => "[comment]",
            .eof => "[eof]",
            .illegal => "[illegal]",
        };
    }
};

pub const TokenType = enum {
    left_paren,
    right_paren,
    left_brace,
    right_brace,
    left_bracket,
    right_bracket,

    at,
    caret,
    colon,
    comma,
    dot,
    dot_dot,
    hash,
    minus,
    percent,
    plus,
    pipe,
    semi_colon,
    slash,
    star,
    tilde,
    minus_equal,
    percent_equal,
    plus_equal,
    slash_equal,
    star_equal,

    bang,
    bang_equal,
    equal,
    equal_equal,
    greater,
    greater_equal,
    less,
    less_equal,

    identifier,
    number,
    string,

    as,
    @"and",
    @"break",
    @"const",
    @"continue",
    @"else",
    @"enum",
    enumseq,
    @"extern",
    false,
    @"fn",
    @"for",
    @"if",
    include,
    list,
    map,
    new,
    nil,
    @"or",
    @"return",
    self,
    seq,
    set,
    class,
    @"switch",
    true,
    @"var",
    void,
    @"while",

    bough,
    divert,
    fork,
    fin,

    comment,
    eof,
    illegal,
};

pub const Keywords = std.StaticStringMap(TokenType).initComptime(.{
    .{ "as", .as },
    .{ "and", .@"and" },
    .{ "bough", .bough },
    .{ "break", .@"break" },
    .{ "continue", .@"continue" },
    .{ "const", .@"const" },
    .{ "else", .@"else" },
    .{ "enum", .@"enum" },
    .{ "enumseq", .enumseq },
    .{ "extern", .@"extern" },
    .{ "false", .false },
    .{ "fn", .@"fn" },
    .{ "for", .@"for" },
    .{ "fork", .fork },
    .{ "fin", .fin },
    .{ "if", .@"if" },
    .{ "include", .include },
    .{ "List", .list },
    .{ "Map", .map },
    .{ "new", .new },
    .{ "nil", .nil },
    .{ "or", .@"or" },
    .{ "return", .@"return" },
    .{ "class", .class },
    .{ "Set", .set },
    .{ "switch", .@"switch" },
    .{ "true", .true },
    .{ "var", .@"var" },
    .{ "void", .void },
    .{ "while", .@"while" },
});

pub fn findType(identifier: []const u8) TokenType {
    return Keywords.get(identifier) orelse .identifier;
}
